import streamlit as st
import time
import json
import datetime
import difflib
from verifhir.remediation.redactor import RedactionEngine

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="VeriFHIR Governance Console",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- BACKEND INITIALIZATION ---
@st.cache_resource
def get_engine():
    """Load the backend engine once; cache for session performance."""
    return RedactionEngine()

engine = get_engine()

# --- HELPER: OPTIMIZED VISUAL DIFF GENERATOR ---
def generate_diff_html(original, redacted):
    """
    Shows original text followed by its redaction tag: Rahul {REDACTED NAME}
    """
    d = difflib.SequenceMatcher(None, original, redacted)
    html = []
    
    for tag, i1, i2, j1, j2 in d.get_opcodes():
        if tag == 'replace':
            # 1. Show the original text (Red Strikethrough)
            html.append(f'<span style="color: #b30000; text-decoration: line-through; padding-right: 4px;">{original[i1:i2]}</span>')
            # 2. Show the suggested tag (Green Chip)
            html.append(f'<span style="background-color: #e6ffed; color: #1a7f37; font-weight: bold; border: 1px solid #2da44e; border-radius: 4px; padding: 2px 6px;">{redacted[j1:j2]}</span>')
        
        elif tag == 'delete':
            html.append(f'<span style="color: #b30000; text-decoration: line-through;">{original[i1:i2]}</span>')
            
        elif tag == 'insert':
            html.append(f'<span style="background-color: #e6ffed; color: #1a7f37; font-weight: bold; border: 1px solid #2da44e; border-radius: 4px; padding: 2px 6px;">{redacted[j1:j2]}</span>')
            
        elif tag == 'equal':
            html.append(original[i1:i2])
            
    return "".join(html)

# --- HELPER: AUDIT DIALOG ---
@st.dialog("Technical Audit Metadata")
def show_audit_dialog(data):
    st.write("### Internal Governance Trace")
    st.json(data)
    st.caption(f"System Reference: {datetime.datetime.now().isoformat()}")
    st.caption("Access restricted to authorized compliance officers only.")

# --- SIDEBAR: SYSTEM CONFIG ---
with st.sidebar:
    st.header("System Control")
    
    st.subheader("Policy Context")
    regulation = st.selectbox(
        "Regulatory Framework", 
        ["HIPAA", "GDPR"],
        help="Applies specific data protection standards based on jurisdiction."
    )
    
    country_code = "US"
    if regulation == "GDPR":
        country_code = st.text_input("Jurisdiction (ISO 3166-1)", "DE").upper()
    
    st.divider()
    
    st.subheader("Engine Intelligence")
    if engine.client:
        st.success("● Hybrid Mode Active")
        st.caption("AI Redactor + Deterministic Fallback")
    else:
        st.warning("● Fallback Mode Active")
        st.caption("Deterministic Pattern Matching Only")

    st.divider()
    st.caption(f"VeriFHIR Core v{engine.PROMPT_VERSION}")

# --- MAIN WORKSPACE ---
st.title("VeriFHIR Governance Console")
st.markdown("#### Clinical Record Remediation & Audit Workspace")

# Legal Guardrail Notice
st.markdown(
    """
    <div style='background-color: #f0f2f6; border-left: 5px solid #007bff; padding: 15px; border-radius: 5px; font-size: 0.95em; color: #1f2937;'>
    <strong>COMPLIANCE NOTICE:</strong> Suggestions generated by Azure OpenAI (GPT-4o). 
    All remediation suggestions require final human attestation before system commit.
    </div>
    <br>
    """,
    unsafe_allow_html=True
)

col_input, col_output = st.columns([1, 1], gap="large")

# --- COLUMN 1: SOURCE RECORD ---
with col_input:
    st.subheader("Source Input")
    
    # Example containing International Phone (+91) and Address
    default_text = (
        "Patient Rahul Sharma (SSN: 123-45-6789) admitted on Jan 12, 2024. "
        "Contact: +91 98765 43210. Resides at 123 Maple Avenue, Apt 4B, NY 10001. "
        "Email: rahul.sharma@example.com."
    )
    
    input_text = st.text_area(
        "Raw Clinical Text",
        height=450,
        value=default_text,
        help="Paste raw patient notes or FHIR resources here."
    )
    
    analyze_btn = st.button("Analyze & Redact", type="primary", use_container_width=True)

# --- ENGINE EXECUTION ---
if "current_result" not in st.session_state:
    st.session_state.current_result = None

if analyze_btn:
    if not input_text.strip():
        st.error("Input required for analysis.")
    else:
        with st.status("Applying governance protocols...", expanded=True) as status:
            response = engine.generate_suggestion(input_text, regulation, country_code)
            st.session_state.current_result = response
            status.update(label="Redaction Complete", state="complete", expanded=False)

# --- COLUMN 2: GOVERNANCE REVIEW ---
with col_output:
    st.subheader("Review Redaction")
    
    if st.session_state.current_result:
        res = st.session_state.current_result
        
        # 1. ENHANCED VISUAL DIFF
        st.markdown("**Proposed Redaction (Redline):**")
        diff_html = generate_diff_html(res['original_text'], res['suggested_redaction'])
        
        st.markdown(
            f"""
            <div style="
                border: 2px solid #e0e6ed; 
                border-radius: 8px; 
                padding: 25px; 
                height: 450px; 
                overflow-y: auto; 
                font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace; 
                white-space: pre-wrap; 
                background-color: #ffffff;
                line-height: 1.8;
                color: #24292e;
                box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 2px 0px;">
                {diff_html}
            </div>
            """, 
            unsafe_allow_html=True
        )
        
        # 2. METADATA FOOTER
        method = res['remediation_method']
        st.caption(f"**Engine Attribution:** {method}")
        
        st.divider()
        
        # 3. ACTION CONTROLS
        st.subheader("Human Attestation")
        
        c1, c2 = st.columns(2)
        with c1:
            if st.button(" Approve & Commit", use_container_width=True):
                st.balloons()
                st.success("Record committed to secure downstream environment.")
                
        with c2:
            if st.button(" Reject & Flag", use_container_width=True):
                st.warning("Flagged for manual remediation queue.")

        st.divider()

        # 4. AUDIT TRACE
        if st.button(" View Technical Audit Metadata", use_container_width=True):
            show_audit_dialog(res)

    else:
        st.info("Awaiting input analysis. Please click 'Analyze & Redact' to generate a proposal.")